### ISSUE TITLE
dataloader error

### ISSUE THREAD

**Issue by Aktcob** [DetectionTeamUCAS/FCOS_GluonCV#2]
for i, batch in enumerate(train_data):
  File "/home/dilu/incubator-mxnet/python/mxnet/gluon/data/dataloader.py", line 443, in next
    return self.__next__()
  File "/home/dilu/incubator-mxnet/python/mxnet/gluon/data/dataloader.py", line 435, in __next__
    batch = pickle.loads(ret.get())
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
mxnet.base.MXNetError: [09:41:17] src/operator/nn/concat.cc:66: Check failed: shape_assign(&(*in_shape)[i], dshape) Incompatible input shape: expected [0,5], got [1,6]

**Comment by Angzz** [comment]
Hi,

We recommend python3 to train this model, and follow the environment
settings in the Readme.

Aktcob <notifications@github.com> 于2019年5月20日周一 上午9:44写道：

**Comment by Aktcob** [comment]
I have fixed this problem. Since the gt bbox of VOC is [l,t,r,b,label,difficulty], which size is 6, not 5. 
This line:     boxes = nd.concat(nd.zeros((1, 5)), boxes, dim=0) # for gt assign confusion
caused the error I mentioned before.
